services:
  # A Docker web service
  - type: web
    name: money-counter
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_KEY
        value: YOUR_TELEGRAM_BOT_KEY